registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/myicr.crt
    REGISTRY_HTTP_TLS_KEY: /certs/myicr.key
    REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
  extra_hosts:
    - "${VG_DOCKER_DOMAIN}:127.0.0.1"
  volumes:
    - ./data:/var/lib/registry
    - ./certs:/certs
